# Generated by Django 5.0.1 on 2024-01-26 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote_application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sign_up',
            old_name='Gmail',
            new_name='gmail',
        ),
        migrations.RenameField(
            model_name='sign_up',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='sign_up',
            old_name='Password',
            new_name='password',
        ),
    ]
