# Generated by Django 5.0.1 on 2024-01-26 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote_application', '0002_rename_gmail_sign_up_gmail_rename_name_sign_up_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sign_up',
        ),
    ]
