# Generated by Django 5.0.1 on 2024-01-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vote_application', '0003_delete_sign_up'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatePoll',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('que', models.CharField(max_length=30)),
                ('polls', models.CharField(max_length=200)),
            ],
        ),
    ]
