# Generated by Django 5.0.1 on 2024-01-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_application', '0005_createpoll_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpoll',
            name='total_vote',
            field=models.IntegerField(default=0, max_length=10000000),
        ),
    ]
