# Generated by Django 5.0.1 on 2024-01-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_application', '0006_createpoll_total_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpoll',
            name='user_gmail',
            field=models.CharField(default='', max_length=50),
        ),
    ]
